name: XShopDynamicShop
version: '${project.version}'
main: net.xsapi.panat.xshop.xshopdynamicshop.core.core
softdepend: [PlayerPoints, XSSeasons]
api-version: '1.20'
authors: [ PanatXsectorZ ]
description: Intelligence Shop For Minecraft Server
aliases: shop
commands:
  xshop:
    description: command for xsapi-dynamicshop plugin
